language: php
php:
  - 5.5
  - 5.4
  - 5.3
env:
  - V8VER=3.22.22
  - V8VER=3.21.12
before_install: make -f Makefile.travis before_install
install: make -f Makefile.travis install
script: make -f Makefile.travis test
